COMMON_SKILLS = [
    "python",
    "flask",
    "django",
    "fastapi",
    "html",
    "css",
    "javascript",
    "typescript",
    "sql",
    "mysql",
    "postgresql",
    "git",
    "github",
    "docker",
    "aws",
    "linux",
    "numpy",
    "pandas",
    "matplotlib",
    "tensorflow",
    "pytorch",
    "opencv",
    "machine learning",
    "data analysis"
]